# Build configuration
build:
  command: npm run build
  output: dist
  environment:
    NODE_VERSION: 18

# Build settings
settings:
  buildCommand: npm run build
  outputDirectory: dist

# Environment variables
environment:
  production:
    VITE_API_BASE_URL: https://bookmarks-api.your-name.workers.dev
    WORKER_HOSTNAME: bookmarks-api.your-name.workers.dev
  preview:
    VITE_API_BASE_URL: https://bookmarks-api.your-name.workers.dev
    WORKER_HOSTNAME: bookmarks-api.your-name.workers.dev