# Build configuration
build:
  command: npm run build
  output: dist
  environment:
    NODE_VERSION: 18

# Build settings
settings:
  buildCommand: npm run build
  outputDirectory: dist

# Environment variables
environment:
  production:
    VITE_API_BASE_URL: https://api.your-domain.com
    WORKER_HOSTNAME: your-worker-name.your-subdomain.workers.dev
  preview:
    VITE_API_BASE_URL: https://preview-api.your-domain.com
    WORKER_HOSTNAME: your-worker-name.your-subdomain.workers.dev