name = "bookmarks-api"
type = "javascript"
account_id = "your-account-id"
workers_dev = true
compatibility_date = "2023-01-01"

# 自定义域名配置
routes = [
  { pattern = "api.your-domain.com/*", zone_id = "your-zone-id" }
]

[vars]
JWT_SECRET = "your-secret-key"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "hashed-password"
MAX_REQUESTS_PER_MINUTE = "100"

[security]
allow_credentials = true
allowed_headers = ["Content-Type", "Authorization", "X-CSRF-Token"]
allowed_methods = ["GET", "POST", "OPTIONS"]
allowed_origins = ["https://your-frontend-domain.com"]

[[kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "your-kv-namespace-id"